2025-01-27 20:11:52,960 - __main__ - INFO - Loading model from D:\Machine Learning\seoul_bike_sharing_demand\models/bike_sharing_model.pkl
2025-01-27 20:11:52,960 - __main__ - INFO - Starting app
2025-01-27 20:11:52,997 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9696
 * Running on http://192.168.100.2:9696
2025-01-27 20:11:52,997 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-01-27 20:11:53,010 - werkzeug - INFO -  * Restarting with watchdog (windowsapi)
2025-01-27 20:11:53,362 - __main__ - INFO - Loading model from D:\Machine Learning\seoul_bike_sharing_demand\models/bike_sharing_model.pkl
2025-01-27 20:11:53,365 - __main__ - INFO - Starting app
2025-01-27 20:11:53,377 - werkzeug - WARNING -  * Debugger is active!
2025-01-27 20:11:53,381 - werkzeug - INFO -  * Debugger PIN: 940-935-887
2025-01-27 23:18:50,066 - app - INFO - Loading model from /mnt/d/Machine Learning/seoul_bike_sharing_demand/models/bike_sharing_model.pkl
2025-01-27 23:20:20,375 - app - INFO - Loading model from /mnt/d/Machine Learning/seoul_bike_sharing_demand/models/bike_sharing_model.pkl
2025-01-27 23:20:20,411 - app - INFO - Starting app
2025-01-27 23:20:20,417 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-01-27 23:20:20,418 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-01-27 23:27:20,131 - app - INFO - Ride data: {'temperature_c': 12.2, 'humidity': 14, 'wind_speed_ms': 1.6, 'visibility_10m': 1896, 'dew_point_temperature_c': -14.5, 'solar_radiation_mjm2': 2.75, 'rainfallmm': 0.0, 'snowfall_cm': 0.0, 'seasons': 'spring', 'holiday': 'no_holiday', 'functioning_day': 'yes', 'month': 3, 'day': 3, 'dayofweek': 5, 'hour_sin': -0.25881904510252035, 'hour_cos': -0.9659258262890684}
2025-01-27 23:27:20,133 - app - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 64, in index
    predict = predict_rented_bike_count(ride)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 80, in predict_rented_bike_count
    model, dv = load_model(MODEL_FILE)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 87, in load_model
    model, dv = pickle.load(file_name)
                ^^^^^^^^^^^^^^^^^^^^^^
TypeError: file must have 'read' and 'readline' attributes
2025-01-27 23:27:20,144 - werkzeug - INFO - 127.0.0.1 - - [27/Jan/2025 23:27:20] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2025-01-27 23:27:39,955 - app - INFO - Ride data: {'temperature_c': 12.2, 'humidity': 14, 'wind_speed_ms': 1.6, 'visibility_10m': 1896, 'dew_point_temperature_c': -14.5, 'solar_radiation_mjm2': 2.75, 'rainfallmm': 0.0, 'snowfall_cm': 0.0, 'seasons': 'spring', 'holiday': 'no_holiday', 'functioning_day': 'yes', 'month': 3, 'day': 3, 'dayofweek': 5, 'hour_sin': -0.25881904510252035, 'hour_cos': -0.9659258262890684}
2025-01-27 23:27:39,956 - app - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 64, in index
    predict = predict_rented_bike_count(ride)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 80, in predict_rented_bike_count
    model, dv = load_model(MODEL_FILE)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 87, in load_model
    model, dv = pickle.load(file_name)
                ^^^^^^^^^^^^^^^^^^^^^^
TypeError: file must have 'read' and 'readline' attributes
2025-01-27 23:27:39,959 - werkzeug - INFO - 127.0.0.1 - - [27/Jan/2025 23:27:39] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2025-01-27 23:35:08,099 - app - INFO - Loading model from /mnt/d/Machine Learning/seoul_bike_sharing_demand/models/bike_sharing_model.pkl
2025-01-27 23:35:08,216 - app - INFO - Starting app
2025-01-27 23:35:08,223 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-01-27 23:35:08,223 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-01-27 23:35:28,521 - app - INFO - Ride data: {'temperature_c': 12.2, 'humidity': 14, 'wind_speed_ms': 1.6, 'visibility_10m': 1896, 'dew_point_temperature_c': -14.5, 'solar_radiation_mjm2': 2.75, 'rainfallmm': 0.0, 'snowfall_cm': 0.0, 'seasons': 'spring', 'holiday': 'no_holiday', 'functioning_day': 'yes', 'month': 3, 'day': 3, 'dayofweek': 5, 'hour_sin': -0.25881904510252035, 'hour_cos': -0.9659258262890684}
2025-01-27 23:35:28,529 - app - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 64, in index
    predict = predict_rented_bike_count(ride)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 80, in predict_rented_bike_count
    model, dv = load_model(MODEL_FILE)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 88, in load_model
    model,dv = pickle.load(f)
               ^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'xgboost'
2025-01-27 23:35:28,538 - werkzeug - INFO - 127.0.0.1 - - [27/Jan/2025 23:35:28] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2025-01-27 23:40:20,930 - app - INFO - Loading model from /mnt/d/Machine Learning/seoul_bike_sharing_demand/models/bike_sharing_model.pkl
2025-01-27 23:40:20,952 - app - INFO - Starting app
2025-01-27 23:40:20,955 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-01-27 23:40:20,955 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-01-27 23:40:36,240 - app - INFO - Ride data: {'temperature_c': 12.2, 'humidity': 14, 'wind_speed_ms': 1.6, 'visibility_10m': 1896, 'dew_point_temperature_c': -14.5, 'solar_radiation_mjm2': 2.75, 'rainfallmm': 0.0, 'snowfall_cm': 0.0, 'seasons': 'spring', 'holiday': 'no_holiday', 'functioning_day': 'yes', 'month': 3, 'day': 3, 'dayofweek': 5, 'hour_sin': -0.25881904510252035, 'hour_cos': -0.9659258262890684}
2025-01-27 23:40:36,309 - app - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 65, in index
    predict = predict_rented_bike_count(ride)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 81, in predict_rented_bike_count
    model, dv = load_model(MODEL_FILE)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 89, in load_model
    model,dv = pickle.load(f)
               ^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'sklearn'
2025-01-27 23:40:36,315 - werkzeug - INFO - 127.0.0.1 - - [27/Jan/2025 23:40:36] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2025-01-27 23:43:07,869 - app - INFO - Loading model from /mnt/d/Machine Learning/seoul_bike_sharing_demand/models/bike_sharing_model.pkl
2025-01-27 23:43:07,958 - app - INFO - Starting app
2025-01-27 23:43:07,961 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-01-27 23:43:07,961 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-01-27 23:43:12,738 - app - INFO - Ride data: {'temperature_c': 12.2, 'humidity': 14, 'wind_speed_ms': 1.6, 'visibility_10m': 1896, 'dew_point_temperature_c': -14.5, 'solar_radiation_mjm2': 2.75, 'rainfallmm': 0.0, 'snowfall_cm': 0.0, 'seasons': 'spring', 'holiday': 'no_holiday', 'functioning_day': 'yes', 'month': 3, 'day': 3, 'dayofweek': 5, 'hour_sin': -0.25881904510252035, 'hour_cos': -0.9659258262890684}
2025-01-27 23:43:12,808 - app - INFO - Loading model and data vectorizer
2025-01-27 23:43:12,814 - app - INFO - Predicted count: [402.90775]
2025-01-27 23:43:12,819 - app - INFO - Saving ride data to database
2025-01-27 23:43:12,832 - app - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 622, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "user"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "user"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 76, in index
    db.session.commit()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4353, in flush
    self._flush(objects)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush
    flush_context.execute()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
    for (
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1753, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in connection
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1039, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1175, in _connection_for_bind
    conn = self._parent._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3274, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2439, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 622, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "user"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "user"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-27 23:43:12,847 - werkzeug - INFO - 127.0.0.1 - - [27/Jan/2025 23:43:12] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2025-01-28 00:06:17,412 - app - INFO - Ride data: {'temperature_c': 12.2, 'humidity': 14, 'wind_speed_ms': 1.6, 'visibility_10m': 1896, 'dew_point_temperature_c': -14.5, 'solar_radiation_mjm2': 2.75, 'rainfallmm': 0.0, 'snowfall_cm': 0.0, 'seasons': 'spring', 'holiday': 'no_holiday', 'functioning_day': 'yes', 'month': 3, 'day': 3, 'dayofweek': 5, 'hour_sin': -0.25881904510252035, 'hour_cos': -0.9659258262890684}
2025-01-28 00:06:17,483 - app - INFO - Loading model and data vectorizer
2025-01-28 00:06:17,503 - app - INFO - Predicted count: [402.90775]
2025-01-28 00:06:17,512 - app - INFO - Saving ride data to database
2025-01-28 00:06:17,527 - app - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 622, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "user"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "user"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 76, in index
    db.session.commit()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4353, in flush
    self._flush(objects)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush
    flush_context.execute()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
    for (
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1753, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in connection
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1039, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1175, in _connection_for_bind
    conn = self._parent._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3274, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2439, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 622, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "user"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "user"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-28 00:06:17,541 - werkzeug - INFO - 127.0.0.1 - - [28/Jan/2025 00:06:17] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2025-01-28 00:07:27,822 - app - INFO - Loading model from /mnt/d/Machine Learning/seoul_bike_sharing_demand/models/bike_sharing_model.pkl
2025-01-28 00:07:27,910 - app - INFO - Starting app
2025-01-28 00:07:27,913 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-01-28 00:07:27,914 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-01-28 00:07:44,383 - app - INFO - Ride data: {'temperature_c': 12.2, 'humidity': 14, 'wind_speed_ms': 1.6, 'visibility_10m': 1896, 'dew_point_temperature_c': -14.5, 'solar_radiation_mjm2': 2.75, 'rainfallmm': 0.0, 'snowfall_cm': 0.0, 'seasons': 'spring', 'holiday': 'no_holiday', 'functioning_day': 'yes', 'month': 3, 'day': 3, 'dayofweek': 5, 'hour_sin': -0.25881904510252035, 'hour_cos': -0.9659258262890684}
2025-01-28 00:07:44,445 - app - INFO - Loading model and data vectorizer
2025-01-28 00:07:44,449 - app - INFO - Predicted count: [402.90775]
2025-01-28 00:07:44,453 - app - INFO - Saving ride data to database
2025-01-28 00:07:44,464 - app - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 622, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "user"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "user"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 76, in index
    db.session.commit()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4353, in flush
    self._flush(objects)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush
    flush_context.execute()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
    for (
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1753, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in connection
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1039, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1175, in _connection_for_bind
    conn = self._parent._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3274, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2439, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 622, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "user"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "user"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-28 00:07:44,474 - werkzeug - INFO - 127.0.0.1 - - [28/Jan/2025 00:07:44] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2025-01-28 00:37:34,606 - app - INFO - Loading model from /mnt/d/Machine Learning/seoul_bike_sharing_demand/models/bike_sharing_model.pkl
2025-01-28 00:37:34,744 - app - INFO - Starting app
2025-01-28 00:37:34,754 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-01-28 00:37:34,754 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-01-28 00:37:46,174 - app - INFO - Ride data: {'temperature_c': 12.2, 'humidity': 14, 'wind_speed_ms': 1.6, 'visibility_10m': 1896, 'dew_point_temperature_c': -14.5, 'solar_radiation_mjm2': 2.75, 'rainfallmm': 0.0, 'snowfall_cm': 0.0, 'seasons': 'spring', 'holiday': 'no_holiday', 'functioning_day': 'yes', 'month': 3, 'day': 3, 'dayofweek': 5, 'hour_sin': -0.25881904510252035, 'hour_cos': -0.9659258262890684}
2025-01-28 00:37:47,317 - app - INFO - Loading model and data vectorizer
2025-01-28 00:37:47,323 - app - INFO - Predicted count: [402.90775]
2025-01-28 00:37:47,326 - app - INFO - Saving ride data to database
2025-01-28 00:37:48,763 - app - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 622, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Machine Learning/seoul_bike_sharing_demand/app.py", line 73, in index
    db.session.commit()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4353, in flush
    self._flush(objects)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush
    flush_context.execute()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
    for (
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1753, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in connection
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1039, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1175, in _connection_for_bind
    conn = self._parent._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3274, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2439, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 622, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.virtualenvs/seoul_bike_sharing_demand/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "db" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-28 00:37:48,775 - werkzeug - INFO - 127.0.0.1 - - [28/Jan/2025 00:37:48] "[35m[1mPOST / HTTP/1.1[0m" 500 -
